version: "3.3"
services:
  familyApp:
    build: familyApp/
    image: "family-app:latest"
    container_name: family-app
    ports:
      - "8054:8054"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  familyMemberApp:
    build: familyMemberApp/
    image: "family-member-app:latest"
    container_name: family-member-app
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  mysqlFamily:
    image: mysql:8.0.28
    container_name: mysql-family-docker
    ports:
      - "33060:3306"
    environment:
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=root
      - MYSQL_DATABASE=familydb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
